In [2]:
import io
import zipfile
import httpx

import pandas as pd
from eutl_scraper.extract import (
    url_source,
    extract_accounts,
    extract_transactions,
    extract_installations,
    extract_compliance
)

## Installations

The file under *Data Download* seem to have all information we need.

In [3]:
df_inst = extract_installations()
#df_inst.info()
df_inst.query(f"installation_id == 'ES_202172'").T

                                                                                         8007
registry_id                                                                                ES
registry_name                                                                           Spain
installation_name                           Aludium Transformación de Productos,S.L.U-Alic...
account_identifier                                                                    5018274
account_registry_code                                                                      ES
account_identifier_in_reg                   Aludium Transformación de Productos, S.L.- Ali...
eper_identification                                                                      3468
activity_type_code                                                                         27
activity_type                                               Production of secondary aluminium
permit_identifier                                                               ES10030810853
permit_revocation_date                                                             2019-08-27
city                                                                                 Alicante
postal_code                                                                             03008
address1                                                                Avenida de Elche, 109
address2                                                                                  NaN
year_of_first_emissions                                                                  2013
year_of_last_emissions                                                                 2019.0
account_holder_company_registration_number                                          B83727255
account_holder_country_code                                                                ES
account_holder_country_name                                                             Spain
account_holder_name                               Aludium Transformación de Productos, S.L.U.
account_holder_lei                                                     5493-007P1WO39TN71P-09
account_holder_city                                                         Amorebieta-Extano
account_holder_postal_code                                                              48340
account_holder_address1                                                 Barrio Ibarguren, s/n
account_holder_address2                                                                   NaN
snapshot_date                                                                      2025-10-21
installation_id                                                                     ES_202172

## Compliance

Also the file under *Download Data* contains most information even including
details on surrendered units, allocation, and the details concerning the Swiss
registry.

In [4]:
df_comp = extract_compliance()
#df_comp.info()

## Accounts

The file from *Data Download* does not contain all data necessary. In particular, 
all firm information is missing.

In [ ]:
df_acc = extract_accounts()
df_acc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47620 entries, 0 to 47619
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   registry_id           47620 non-null  object
 1   registry_name         47620 non-null  object
 2   account_name          47620 non-null  object
 3   account_type          47620 non-null  object
 4   ets_account_type      28302 non-null  object
 5   full_type             47591 non-null  object
 6   open_date             47584 non-null  object
 7   end_of_validity_date  47620 non-null  object
 8   snapshot_date         47620 non-null  object
 9   account_id            47620 non-null  object
 10  account_type_id       47595 non-null  object
 11  closure_pending       47620 non-null  bool
dtypes: bool(1), object(11)
memory usage: 4.0+ MB

The table that can be downloaded through the PowerBi app seems to have the missing
information on account holders. We need, however, to clarify why there are more
accounts in the "Download Data" file.

In [7]:
fn_acc = "./data/accounts_all.xlsx"
df_acc = pd.read_excel(fn_acc)
df_acc.info()

c:\GIT\eutl_scraper_v2\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47345 entries, 0 to 47344
Data columns (total 15 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Account Identifier                                   47344 non-null  object
 1   National Administrator                               47343 non-null  object
 2   Account Type                                         47343 non-null  object
 3   Account Holder Name                                  47343 non-null  object
 4   Account Name                                         47343 non-null  object
 5   Installation/Aircraft Operator/Maritime Operator ID  22120 non-null  float64
 6   Company Registration No                              42735 non-null  object
 7   Main Address Line                                    47334 non-null  object
 8   City                                                 47334 non-null  object
 9   Legal Entity Identifier                              8943 non-null   object
 10  Telephone 1                                          731 non-null    object
 11  Telephone 2                                          603 non-null    object
 12  Email                                                794 non-null    object
 13  .                                                    47343 non-null  float64
 14  ..1                                                  47343 non-null  object
dtypes: float64(2), object(13)
memory usage: 5.4+ MB

## Transactions

In [9]:
df_trans = extract_transactions()
df_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1875818 entries, 0 to 1875817
Data columns (total 65 columns):
 #   Column                                                   Dtype
---  ------                                                   -----
 0   TRANSACTION_ID                                           object
 1   TRANSACTION_TYPE                                         object
 2   TRANSACTION_DATE                                         object
 3   TRANSACTION_STATUS                                       object
 4   TRANSFERRING_REGISTRY_NAME                               object
 5   TRANSFERRING_ACCOUNT_TYPE                                float64
 6   TRANSFERRING_ACCOUNT_TYPE2                               object
 7   TRANSFERRING_ACCOUNT_OPEN_DT                             object
 8   TRANSFERRING_ACCOUNT_END_OF_VALIDITY                     object
 9   TRANSFERRING_ACCOUNT_NAME                                object
 10  TRANSFERRING_ACCOUNT_IDENTIFIER                          float64
 11  TRANSFERRING_ACCOUNT_HOLDER                              object
 12  TRANSFERRING_ACCOUNT_HOLDER_ADDRESS1                     object
 13  TRANSFERRING_ACCOUNT_HOLDER_ADDRESS2                     object
 14  TRANSFERRING_ACCOUNT_HOLDER_CITY                         object
 15  TRANSFERRING_ACCOUNT_HOLDER_POSTAL_CODE                  object
 16  TRANSFERRING_ACCOUNT_HOLDER_COUNTRY_CODE                 object
 17  TRANSFERRING_ACCOUNT_HOLDER_COMPANY_REGISTRATION_NUMBER  object
 18  TRANSFERRING_ACCOUNT_HOLDER_LEI                          object
 19  TRANSFERRING_INSTALLATION_NAME                           object
 20  TRANSFERRING_INSTALLATION_INSTALLATION_IDENTIFIER        float64
 21  TRANSFERRING_INSTALLATION_PERMIT_IDENTIFIER              object
 22  TRANSFERRING_INSTALLATION_PARENT_COMPANY                 object
 23  TRANSFERRING_INSTALLATION_SUBSIDIARY_COMPANY             object
 24  TRANSFERRING_INSTALLATION_EPER_IDENTIFICATION            object
 25  TRANSFERRING_INSTALLATION_CITY                           object
 26  TRANSFERRING_INSTALLATION_POSTAL_CODE                    object
 27  TRANSFERRING_INSTALLATION_ADDRESS1                       object
 28  TRANSFERRING_INSTALLATION_ADDRESS2                       object
 29  TRANSFERRING_INSTALLATION_MAIN_ACTIVITY                  object
 30  ACQUIRING_REGISTRY_NAME                                  object
 31  ACQUIRING_ACCOUNT_TYPE                                   int64
 32  ACQUIRING_ACCOUNT_ACCOUNT_TYPE2                          object
 33  ACQUIRING_ACCOUNT_OPEN_DT                                object
 34  ACQUIRING_ACCOUNT_END_OF_VALIDITY                        object
 35  ACQUIRING_ACCOUNT_NAME                                   object
 36  ACQUIRING_ACCOUNT_IDENTIFIER                             int64
 37  ACQUIRING_ACCOUNT_HOLDER                                 object
 38  ACQUIRING_ACCOUNT_HOLDER_ADDRESS1                        object
 39  ACQUIRING_ACCOUNT_HOLDER_ADDRESS2                        object
 40  ACQUIRING_ACCOUNT_HOLDER_CITY                            object
 41  ACQUIRING_ACCOUNT_HOLDER_POSTAL_CODE                     object
 42  ACQUIRING_ACCOUNT_HOLDER_COUNTRY_CODE                    object
 43  ACQUIRING_ACCOUNT_HOLDER_COMPANY_REGISTRATION_NUMBER     object
 44  ACQUIRING_ACCOUNT_HOLDER_LEI                             object
 45  ACQUIRING_INSTALLATION_NAME                              object
 46  ACQUIRING_INSTALLATION_INSTALLATION_IDENTIFIER           float64
 47  ACQUIRING_INSTALLATION_PERMIT_IDENTIFIER                 object
 48  ACQUIRING_INSTALLATION_PARENT_COMPANY                    object
 49  ACQUIRING_INSTALLATION_SUBSIDIARY_COMPANY                object
 50  ACQUIRING_INSTALLATION_EPER_IDENTIFICATION               object
 51  ACQUIRING_INSTALLATION_CITY                              object
 52  ACQUIRING_INSTALLATION_POSTAL_CODE                       object
 53  ACQUIRING_INSTALLATION_ADDRESS1                          object
 54  ACQUIRING_INSTALLATION_ADDRESS2                          object
 55  ACQUIRING_INSTALLATION_MAIN_ACTIVITY                     object
 56  ORIGINATING_REGISTRY                                     object
 57  UNIT_TYPE_DESCRIPTION                                    object
 58  SUPP_UNIT_TYPE_DESCRIPTION                               object
 59  ORIGINAL_PERIOD_CODE                                     int64
 60  LULUCF_CODE_DESCRIPTION                                  object
 61  PROJECT_IDENTIFIER                                       float64
 62  TRACK                                                    float64
 63  EXPIRY_DATE                                              object
 64  AMOUNT                                                   int64
dtypes: float64(6), int64(4), object(55)
memory usage: 930.2+ MB

In [3]:
df.columns

Index(['TRANSACTION_ID', 'TRANSACTION_TYPE', 'TRANSACTION_DATE',
       'TRANSACTION_STATUS', 'TRANSFERRING_REGISTRY_NAME',
       'TRANSFERRING_ACCOUNT_TYPE', 'TRANSFERRING_ACCOUNT_TYPE2',
       'TRANSFERRING_ACCOUNT_OPEN_DT', 'TRANSFERRING_ACCOUNT_END_OF_VALIDITY',
       'TRANSFERRING_ACCOUNT_NAME', 'TRANSFERRING_ACCOUNT_IDENTIFIER',
       'TRANSFERRING_ACCOUNT_HOLDER', 'TRANSFERRING_ACCOUNT_HOLDER_ADDRESS1',
       'TRANSFERRING_ACCOUNT_HOLDER_ADDRESS2',
       'TRANSFERRING_ACCOUNT_HOLDER_CITY',
       'TRANSFERRING_ACCOUNT_HOLDER_POSTAL_CODE',
       'TRANSFERRING_ACCOUNT_HOLDER_COUNTRY_CODE',
       'TRANSFERRING_ACCOUNT_HOLDER_COMPANY_REGISTRATION_NUMBER',
       'TRANSFERRING_ACCOUNT_HOLDER_LEI', 'TRANSFERRING_INSTALLATION_NAME',
       'TRANSFERRING_INSTALLATION_INSTALLATION_IDENTIFIER',
       'TRANSFERRING_INSTALLATION_PERMIT_IDENTIFIER',
       'TRANSFERRING_INSTALLATION_PARENT_COMPANY',
       'TRANSFERRING_INSTALLATION_SUBSIDIARY_COMPANY',
       'TRANSFERRING_INSTALLATION_EPER_IDENTIFICATION',
       'TRANSFERRING_INSTALLATION_CITY',
       'TRANSFERRING_INSTALLATION_POSTAL_CODE',
       'TRANSFERRING_INSTALLATION_ADDRESS1',
       'TRANSFERRING_INSTALLATION_ADDRESS2',
       'TRANSFERRING_INSTALLATION_MAIN_ACTIVITY', 'ACQUIRING_REGISTRY_NAME',
       'ACQUIRING_ACCOUNT_TYPE', 'ACQUIRING_ACCOUNT_ACCOUNT_TYPE2',
       'ACQUIRING_ACCOUNT_OPEN_DT', 'ACQUIRING_ACCOUNT_END_OF_VALIDITY',
       'ACQUIRING_ACCOUNT_NAME', 'ACQUIRING_ACCOUNT_IDENTIFIER',
       'ACQUIRING_ACCOUNT_HOLDER', 'ACQUIRING_ACCOUNT_HOLDER_ADDRESS1',
       'ACQUIRING_ACCOUNT_HOLDER_ADDRESS2', 'ACQUIRING_ACCOUNT_HOLDER_CITY',
       'ACQUIRING_ACCOUNT_HOLDER_POSTAL_CODE',
       'ACQUIRING_ACCOUNT_HOLDER_COUNTRY_CODE',
       'ACQUIRING_ACCOUNT_HOLDER_COMPANY_REGISTRATION_NUMBER',
       'ACQUIRING_ACCOUNT_HOLDER_LEI', 'ACQUIRING_INSTALLATION_NAME',
       'ACQUIRING_INSTALLATION_INSTALLATION_IDENTIFIER',
       'ACQUIRING_INSTALLATION_PERMIT_IDENTIFIER',
       'ACQUIRING_INSTALLATION_PARENT_COMPANY',
       'ACQUIRING_INSTALLATION_SUBSIDIARY_COMPANY',
       'ACQUIRING_INSTALLATION_EPER_IDENTIFICATION',
       'ACQUIRING_INSTALLATION_CITY', 'ACQUIRING_INSTALLATION_POSTAL_CODE',
       'ACQUIRING_INSTALLATION_ADDRESS1', 'ACQUIRING_INSTALLATION_ADDRESS2',
       'ACQUIRING_INSTALLATION_MAIN_ACTIVITY', 'ORIGINATING_REGISTRY',
       'UNIT_TYPE_DESCRIPTION', 'SUPP_UNIT_TYPE_DESCRIPTION',
       'ORIGINAL_PERIOD_CODE', 'LULUCF_CODE_DESCRIPTION', 'PROJECT_IDENTIFIER',
       'TRACK', 'EXPIRY_DATE', 'AMOUNT'],
      dtype='object')

In [10]:
map_col = {
    "REGISTRY_CODE": "registry_id",
}
df = (
        df_comp
        .assign(
            installation_id=lambda df: df.REGISTRY_CODE
            + "_"
            + df.INSTALLATION_IDENTIFIER.astype(str)
        )
        .drop(columns=["INSTALLATION_IDENTIFIER"])
        .rename(columns=map_col)
        .rename(columns=lambda x: x.lower())
    )

In [8]:
df_comp.head()

   INSTALLATION_IDENTIFIER REGISTRY_CODE  ... SURR_ALL SNAPSHOT_DATE
0                        1            AT  ...  41399.0    2025-10-13
1                        1            AT  ...     -1.0    2025-10-13
2                        1            AT  ...  51041.0    2025-10-13
3                        1            AT  ...  57009.0    2025-10-13
4                        1            AT  ...  44299.0    2025-10-13

[5 rows x 23 columns]