In [1]:
from pathlib import Path
import pandas as pd

In [4]:
dir_extracted = Path("./data_tmp/extracted/")
fn_trans = dir_extracted / "eutl_transactions.csv"
fn_inst = dir_extracted / "eutl_installations.csv"
fn_accounts = dir_extracted / "eutl_accounts.csv"
fn_holders = dir_extracted / "eutl_account_holders.csv"
fn_compliance = dir_extracted / "eutl_compliance.csv"
fn_projects = dir_extracted / "eutl_projects.csv"
fn_trans = dir_extracted / "eutl_transactions.csv"
fn_parties = dir_extracted / "eutl_transaction_parties.csv"
fn_locations = dir_extracted / "installation_locations.csv"
fn_nace_mapping = dir_extracted / "nace_from_leakage_lists.csv"
fn_eex = dir_extracted / "eex_auctions.csv"

fn_old_installation_data = Path(
    "manual_data/installations_euets_info_historical_batches.parquet"
)

## Missing installations

In [14]:
df_compliance = pd.read_csv(fn_compliance)
df_old_inst = pd.read_parquet(fn_old_installation_data)
df_inst = pd.read_csv(fn_inst)

inst_compl = set(df_compliance["installation_id"].unique())
inst_old = set(df_old_inst["id"].unique())
inst_new = set(df_inst["installation_id"].unique())

missing_new = inst_compl - inst_new
print(f"installations in compliance but not in new data: {len(missing_new)}")
in_old_data = missing_new.intersection(inst_old)
print(f"installations in compliance but not in new data, but in old data: {len(in_old_data)}")
for i in missing_new:
    if i in in_old_data:
        print(f"installation {i} is in old data")
    else:
        print(f"installation {i} is missing in both new and old data")

installations in compliance but not in new data: 7768
installations in compliance but not in new data, but in old data: 6538
installation ES_231900 is missing in both new and old data
installation NL_220642 is in old data
installation SE_83 is in old data
installation NO_9 is in old data
installation SE_639 is in old data
installation DE_227280 is missing in both new and old data
installation DE_1428 is in old data
installation CZ_213 is in old data
installation DE_31 is in old data
installation FR_200132 is in old data
installation IT_580 is in old data
installation ES_202561 is in old data
installation FR_309 is in old data
installation NO_68 is in old data
installation NO_200307 is in old data
installation ES_90002 is in old data
installation PL_202698 is in old data
installation CY_227925 is missing in both new and old data
installation FR_135 is in old data
installation DE_1678 is in old data
installation LV_32 is in old data
installation ES_266 is in old data
installation GB_265 is in old data
installation NL_225700 is missing in both new and old data
installation GB_736 is in old data
installation MT_214760 is in old data
installation FR_995 is in old data
installation CY_224826 is missing in both new and old data
installation IT_203816 is in old data
installation DE_680 is in old data
installation DE_3901 is in old data
installation SE_219320 is in old data
installation DE_833 is in old data
installation EE_55 is in old data
installation DE_4100 is in old data
installation RO_76 is in old data
installation GB_295 is in old data
installation NL_228040 is missing in both new and old data
installation PL_210474 is in old data
installation NL_359 is in old data
installation LT_113 is in old data
installation SK_28 is in old data
installation PL_418 is in old data
installation PL_203186 is in old data
installation GR_206054 is in old data
installation SE_786 is in old data
installation DK_70 is in old data
installation ES_763 is in old data
installation GB_670 is in old data
installation SE_762 is in old data
installation ES_724 is in old data
installation NL_105 is in old data
installation GR_229169 is missing in both new and old data
installation ES_367 is in old data
installation ES_90044 is in old data
installation SE_353 is in old data
installation DE_891 is in old data
installation IT_202535 is in old data
installation ES_147 is in old data
installation DE_1146 is in old data
installation DE_85 is in old data
installation ES_229468 is missing in both new and old data
installation ES_478 is in old data
installation IT_224282 is missing in both new and old data
installation IT_224160 is missing in both new and old data
installation ES_1059 is in old data
installation GR_147 is in old data
installation GB_443 is in old data
installation DE_205983 is in old data
installation FR_200467 is in old data
installation CZ_367 is in old data
installation DK_90 is in old data
installation GR_222684 is in old data
installation FR_390 is in old data
installation GB_201905 is in old data
installation PL_154 is in old data
installation DE_201938 is in old data
installation PL_824 is in old data
installation IT_222202 is in old data
installation FR_230009 is missing in both new and old data
installation DE_384 is in old data
installation SE_502 is in old data
installation PL_429 is in old data
installation NL_205728 is in old data
installation HR_204297 is in old data
installation DE_209146 is in old data
installation GR_223451 is missing in both new and old data
installation NL_228605 is missing in both new and old data
installation RO_13 is in old data
installation GB_1257 is in old data
installation IT_690 is in old data
installation PL_227108 is missing in both new and old data
installation IE_13 is in old data
installation GB_837 is in old data
installation IT_57 is in old data
installation GB_779 is in old data
installation DE_1005 is in old data
installation SK_155 is in old data
installation GR_221050 is in old data
installation FI_231 is in old data
installation DE_1344 is in old data
installation ES_224702 is missing in both new and old data
installation PL_621 is in old data
installation RO_266 is in old data
installation NL_223602 is missing in both new and old data
installation BE_224 is in old data
installation EE_46 is in old data
installation GR_204153 is in old data
installation IT_221166 is in old data
installation FR_230267 is missing in both new and old data
installation FR_203713 is in old data
installation GR_224322 is missing in both new and old data
installation GR_221210 is in old data
installation FR_204087 is in old data
installation BE_225240 is missing in both new and old data
installation SE_109 is in old data
installation IT_1035 is in old data
installation SE_58 is in old data
installation FR_201425 is in old data
installation DK_34 is in old data
installation FR_614 is in old data
installation LT_228560 is missing in both new and old data
installation DE_223461 is missing in both new and old data
installation FR_488 is in old data
installation DK_77 is in old data
installation SE_223 is in old data
installation PL_171 is in old data
installation DE_200316 is in old data
installation NL_225301 is missing in both new and old data
installation SK_201510 is in old data
installation IT_1089 is in old data
installation PL_426 is in old data
installation GB_203092 is in old data
installation FR_205787 is in old data
installation PT_43 is in old data
installation ES_201628 is in old data
installation ES_124 is in old data
installation GR_222167 is in old data
installation PL_111 is in old data
installation HU_125 is in old data
installation FR_37 is in old data
installation SE_657 is in old data
installation SE_263 is in old data
installation RO_229770 is missing in both new and old data
installation IT_804 is in old data
installation GB_206523 is in old data
installation FR_740 is in old data
installation DE_1078 is in old data
installation SI_24 is in old data
installation BG_98 is in old data
installation IT_889 is in old data
installation SI_74 is in old data
installation IE_202919 is in old data
installation GB_822 is in old data
installation GB_202157 is in old data
installation NO_232507 is missing in both new and old data
installation DK_330 is in old data
installation CZ_262 is in old data
installation SE_443 is in old data
installation ES_227270 is missing in both new and old data
installation BG_136 is in old data
installation ES_203775 is in old data
installation DE_929 is in old data
installation FR_220 is in old data
installation AT_220647 is missing in both new and old data
installation CZ_407 is in old data
installation PL_501 is in old data
installation HU_170 is in old data
installation BE_205762 is in old data
installation FR_228003 is missing in both new and old data
installation NO_221501 is in old data
installation DE_1491 is in old data
installation GR_228323 is missing in both new and old data
installation DE_1111 is in old data
installation CZ_55 is in old data
installation BE_228420 is missing in both new and old data
installation CZ_203591 is in old data
installation SE_66 is in old data
installation PL_914 is in old data
installation GR_225765 is missing in both new and old data
installation IT_201769 is in old data
installation PL_695 is in old data
installation GB_764 is in old data
installation ES_225445 is missing in both new and old data
installation GB_201983 is in old data
installation PL_433 is in old data
installation DE_200661 is in old data
installation ES_364 is in old data
installation DE_1605 is in old data
installation IT_448 is in old data
installation GB_451 is in old data
installation ES_227434 is missing in both new and old data
installation FR_205688 is in old data
installation GB_346 is in old data
installation GB_619 is in old data
installation RO_95 is in old data
installation NO_202608 is in old data
installation SE_112 is in old data
installation ES_877 is in old data
installation NO_36 is in old data
installation SE_441 is in old data
installation PL_503 is in old data
installation DE_202526 is in old data
installation IT_624 is in old data
installation RO_39 is in old data
installation ES_1053 is in old data
installation IT_201849 is in old data
installation DE_222440 is missing in both new and old data
installation DE_692 is in old data
installation GR_224620 is missing in both new and old data
installation GB_214300 is in old data
installation FR_204088 is in old data
installation DE_422 is in old data
installation PL_413 is in old data
installation GB_422 is in old data
installation BE_225030 is missing in both new and old data
installation FR_319 is in old data
installation DE_223200 is missing in both new and old data
installation DK_372 is in old data
installation ES_206169 is in old data
installation GR_226423 is missing in both new and old data
installation FR_1125 is in old data
installation GR_221003 is in old data
installation FR_212401 is in old data
installation DE_203081 is in old data
installation HU_26 is in old data
installation ES_853 is in old data
installation NO_223363 is missing in both new and old data
installation FR_206622 is in old data
installation DE_836 is in old data
installation FR_278 is in old data
installation DE_223161 is missing in both new and old data
installation FI_142 is in old data
installation SE_186 is in old data
installation SI_3 is in old data
installation SE_348 is in old data
installation BE_204195 is in old data
installation GR_222250 is in old data
installation BE_760 is in old data
installation GB_210203 is in old data
installation GB_821 is in old data
installation SK_80 is in old data
installation LT_97 is in old data
installation FR_241 is in old data
installation DE_205912 is in old data
installation FR_204319 is in old data
installation IT_1073 is in old data
installation DE_1440 is in old data
installation RO_23 is in old data
installation SE_595 is in old data
installation DE_1806 is in old data
installation ES_90011 is in old data
installation LT_33 is in old data
installation SE_207654 is in old data
installation NO_105 is in old data
installation ES_205958 is in old data
installation DE_902 is in old data
installation GR_216840 is in old data
installation PL_565 is in old data
installation GB_1024 is in old data
installation GB_205950 is in old data
installation FR_202694 is in old data
installation SE_212038 is in old data
installation PL_202254 is in old data
installation DE_205270 is in old data
installation DE_835 is in old data
installation FR_1159 is in old data
installation FI_258 is in old data
installation IT_202341 is in old data
installation DE_211198 is in old data
installation ES_485 is in old data
installation FR_251 is in old data
installation DE_268 is in old data
installation FR_206028 is in old data
installation GB_205666 is in old data
installation ES_229682 is missing in both new and old data
installation ES_939 is in old data
installation RO_201 is in old data
installation DE_1661 is in old data
installation GR_125 is in old data
installation DE_201963 is in old data
installation FI_659 is in old data
installation IT_227306 is missing in both new and old data
installation DE_215460 is in old data
installation DE_147 is in old data
installation ES_202503 is in old data
installation SE_714 is in old data
installation NL_222 is in old data
installation IT_202571 is in old data
installation DE_201689 is in old data
installation FR_666 is in old data
installation GB_726 is in old data
installation BG_102 is in old data
installation LT_42 is in old data
installation GB_499 is in old data
installation PT_25 is in old data
installation BE_211 is in old data
installation DK_32 is in old data
installation AT_200103 is in old data
installation GR_228327 is missing in both new and old data
installation CZ_298 is in old data
installation DK_213 is in old data
installation FR_227392 is missing in both new and old data
installation DE_1658 is in old data
installation ES_226744 is missing in both new and old data
installation NL_79 is in old data
installation CZ_188 is in old data
installation AT_231 is in old data
installation ES_225343 is missing in both new and old data
installation IT_203479 is in old data
installation FR_214181 is in old data
installation BE_227096 is missing in both new and old data
installation NL_229389 is missing in both new and old data
installation DE_1413 is in old data
installation IT_206953 is in old data
installation DE_202342 is in old data
installation AT_236 is in old data
installation FI_311 is in old data
installation ES_229517 is missing in both new and old data
installation FR_514 is in old data
installation BE_205932 is in old data
installation SE_390 is in old data
installation PT_74 is in old data
installation FR_660 is in old data
installation SE_104 is in old data
installation ES_224661 is missing in both new and old data
installation SE_162 is in old data
installation ES_207082 is in old data
installation ES_224 is in old data
installation PL_183 is in old data
installation GB_210669 is in old data
installation ES_225793 is missing in both new and old data
installation PT_131 is in old data
installation IT_546 is in old data
installation FR_1067 is in old data
installation NL_46 is in old data
installation GR_220944 is in old data
installation PL_555 is in old data
installation IT_180 is in old data
installation IS_203374 is in old data
installation GB_205043 is in old data
installation DE_485 is in old data
installation DE_793 is in old data
installation AT_203413 is in old data
installation DE_1296 is in old data
installation PL_498 is in old data
installation DE_203183 is in old data
installation RO_263 is in old data
installation FR_732 is in old data
installation IT_483 is in old data
installation GB_1057 is in old data
installation DE_1702 is in old data
installation DE_205246 is in old data
installation PT_15 is in old data
installation DE_210625 is in old data
installation IT_229903 is missing in both new and old data
installation PL_664 is in old data
installation LV_83 is in old data
installation SI_80 is in old data
installation DE_1276 is in old data
installation FR_203914 is in old data
installation ES_1056 is in old data
installation GB_210302 is in old data
installation SE_211081 is in old data
installation ES_160 is in old data
installation DE_1867 is in old data
installation DE_202007 is in old data
installation PT_254 is in old data
installation ES_656 is in old data
installation FR_426 is in old data
installation DE_1483 is in old data
installation NL_436 is in old data
installation DE_3194 is in old data
installation FR_336 is in old data
installation DE_1343 is in old data
installation FI_606 is in old data
installation PT_149 is in old data
installation GR_222265 is in old data
installation DE_687 is in old data
installation IE_203787 is in old data
installation PL_911 is in old data
installation BE_49 is in old data
installation GB_569 is in old data
installation DK_134 is in old data
installation DE_1105 is in old data
installation EE_25 is in old data
installation SK_190 is in old data
installation GB_206962 is in old data
installation GB_200353 is in old data
installation ES_90068 is in old data
installation DE_1813 is in old data
installation FR_206343 is in old data
installation GB_6 is in old data
installation NO_225362 is missing in both new and old data
installation FR_205576 is in old data
installation FI_143 is in old data
installation FR_201669 is in old data
installation NL_223722 is missing in both new and old data
installation GR_77 is in old data
installation IT_205315 is in old data
installation PT_20 is in old data
installation GB_855 is in old data
installation DE_135 is in old data
installation ES_226625 is missing in both new and old data
installation FI_510 is in old data
installation GB_461 is in old data
installation DE_223908 is missing in both new and old data
installation DE_1667 is in old data
installation NL_232200 is missing in both new and old data
installation FI_454 is in old data
installation DE_224004 is missing in both new and old data
installation PT_30 is in old data
installation GB_200088 is in old data
installation IT_214862 is in old data
installation IT_228222 is missing in both new and old data
installation PL_507 is in old data
installation ES_229308 is missing in both new and old data
installation PL_873 is in old data
installation DE_223452 is missing in both new and old data
installation ES_376 is in old data
installation NL_229110 is missing in both new and old data
installation FR_203400 is in old data
installation GB_227 is in old data
installation NL_410 is in old data
installation IT_224669 is missing in both new and old data
installation DE_223826 is missing in both new and old data
installation PL_202697 is in old data
installation ES_226973 is missing in both new and old data
installation DE_222226 is missing in both new and old data
installation GB_892 is in old data
installation NL_201276 is in old data
installation PL_842 is in old data
installation LV_9 is in old data
installation ES_203565 is in old data
installation DK_128 is in old data
installation NL_226911 is missing in both new and old data
installation BG_22 is in old data
installation GR_220920 is in old data
installation CZ_203469 is in old data
installation FI_312 is in old data
installation DE_208973 is in old data
installation GB_206919 is in old data
installation DE_207569 is in old data
installation DE_222129 is missing in both new and old data
installation NL_229427 is missing in both new and old data
installation ES_229806 is missing in both new and old data
installation FR_202338 is in old data
installation BE_223630 is missing in both new and old data
installation FR_1136 is in old data
installation BE_273 is in old data
installation DE_210525 is in old data
installation FI_313 is in old data
installation SE_203005 is in old data
installation PL_294 is in old data
installation GR_227436 is missing in both new and old data
installation PL_752 is in old data
installation DK_155 is in old data
installation NL_229426 is missing in both new and old data
installation FR_353 is in old data
installation FR_60 is in old data
installation IT_217600 is in old data
installation PL_210720 is in old data
installation GB_49 is in old data
installation GB_952 is in old data
installation PL_487 is in old data
installation IT_814 is in old data
installation SE_218760 is in old data
installation PT_284 is in old data
installation FR_206301 is in old data
installation BE_205717 is in old data
installation DE_1814 is in old data
installation SE_202299 is in old data
installation FR_787 is in old data
installation GR_140 is in old data
installation LV_200081 is in old data
installation IT_314 is in old data
installation ES_207063 is in old data
installation PL_151 is in old data
installation FR_908 is in old data
installation DE_203756 is in old data
installation ES_28054674 is in old data
installation DE_1042 is in old data
installation FR_202995 is in old data
installation IT_496 is in old data
installation GB_201572 is in old data
installation SE_664 is in old data
installation LV_7 is in old data
installation IT_986 is in old data
installation NL_205674 is in old data
installation ES_229954 is missing in both new and old data
installation FR_530 is in old data
installation ES_90052 is in old data
installation FI_545 is in old data
installation PL_202 is in old data
installation GR_229925 is missing in both new and old data
installation HR_203867 is in old data
installation CZ_387 is in old data
installation FR_238 is in old data
installation FR_201357 is in old data
installation NO_13 is in old data
installation IT_1013 is in old data
installation IT_1140 is in old data
installation FR_106 is in old data
installation DE_201957 is in old data
installation GB_202870 is in old data

In [12]:
inst_id = list(missing_new)[0]
for inst_id in list(missing_new):
    df_ = (
        df_compliance[df_compliance["installation_id"] == inst_id]
        .drop_duplicates(subset=["installation_name"])
    )
    if len(df_) > 1:
        print("!!!!Inconsistent!!!!")
        print(df_[["installation_id", "installation_name"]])
        continue
    print(df_.iloc[0]["installation_id"],df_.iloc[0]["installation_name"])

NO_228641 Nasjonal konto - ETS2
LV_228662 LV_ETS2
GR_228702 GR_ETS2
LT_228560 ES ATLPS2 (LT)
AT_228500 ETS2 Mitgliedstaat Konto Österreich
ES_228683 Cuenta anotación emisiones agregadas 2024 y 2025 – RCDE2
DE_228580 ETS2 -DE-Konto
HR_228647 ETS2 nacionalni račun
EE_228681 Eesti HKS2 konto
BE_228684 ETS2 BE account
IT_228642 Conto nazionale ETS2
LU_228687 LU ETS2 NCA Account
DK_228660 National ETS2konto
SK_228610 Účet príslušného vnútroštátneho orgánu
MT_228601 Climate Action Authority
NL_228600 ETS2 Netherlands
RO_228804 AGENTIA NATIONALA PENTRU MEDIU SI ARII PROTEJATE
CZ_228618 ETS2 účet České republiky
FI_228581 ETS2 National Competent Authority Account
IE_228689 National Competent Authority Account - ETS2
SE_228584 Sveriges nationella ETS2-konto
PL_229400 Rachunek krajowy ETS2
SI_228583 SI ETS2 račun
BG_229520 National Competent Authority Account
FR_228686 Compte FR ETS2

In [13]:
df_compliance

,installation_id,installation_name,registry_id,registry_name,year,allocated,allocated_ch,allocation_res,allocation_tra,verified,...,surrendered_chu,surrendered_chua,surrendered_eru_from_aau,surrendered_former_eua,surrendered_cer,excluded,ch_excluded,snapshot_date,snapshot_date.1,created_at
0,AT_1,Calmit Bad Ischl,AT,Austria,2005,44894.0,NaN,0.0,0.0,41399.0,...,NaN,NaN,NaN,NaN,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180
1,AT_1,Calmit Bad Ischl,AT,Austria,2025,33216.0,NaN,0.0,0.0,41848.0,...,NaN,NaN,NaN,NaN,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180
2,AT_1,Calmit Bad Ischl,AT,Austria,2007,44894.0,NaN,0.0,0.0,51041.0,...,NaN,NaN,NaN,NaN,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180
3,AT_1,Calmit Bad Ischl,AT,Austria,2008,43171.0,NaN,0.0,0.0,57009.0,...,NaN,NaN,NaN,57009.0,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180
4,AT_1,Calmit Bad Ischl,AT,Austria,2009,43171.0,NaN,0.0,0.0,44299.0,...,NaN,NaN,NaN,44299.0,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471445,XI_219000,EP NI Energy Limited,XI,Northern Ireland,2022,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180
471446,XI_219000,EP NI Energy Limited,XI,Northern Ireland,2023,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180
471447,XI_219000,EP NI Energy Limited,XI,Northern Ireland,2024,NaN,NaN,NaN,NaN,282276.0,...,NaN,NaN,NaN,NaN,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180
471448,XI_219000,EP NI Energy Limited,XI,Northern Ireland,2025,NaN,NaN,NaN,NaN,642084.0,...,NaN,NaN,NaN,NaN,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180
471449,XI_219000,EP NI Energy Limited,XI,Northern Ireland,2005,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,False,False,2026-04-14,2026-04-14,2026-04-14 16:47:15.774180

## Missing accounts

In [8]:
df_accounts = pd.read_csv(fn_accounts, low_memory=False)
df_parties = pd.read_csv(fn_parties, low_memory=False)

In [9]:
# get the missing account ids
account_ids = set(df_accounts["account_id"])
party_account_ids = set(df_parties["account_id"])
missing_account_ids = party_account_ids - account_ids
print(f"{len(missing_account_ids)} missing account IDs")
print(missing_account_ids)

762 missing account IDs
{'JP_54', 'CH_49', 'CH_46', 'CDM_1004', 'CH_72', 'CH_116', 'GB_5019359', 'CH_54', 'CDM_2068', 'GB_5017604', 'CH_93', 'CDM_2078', 'NZ_1053', 'AU_2977', 'CH_95', 'CDM_2038', 'GB_5018854', 'CDM_2083', 'CH_685', 'GB_5017528', 'CH_511', 'CH_389', 'CH_684', 'CH_91', 'CH_2206', 'GB_5024090', 'CH_390', 'CH_638', 'AU_1066', 'CDM_2208', 'AU_2931', 'GB_5000777', 'CH_96', 'CH_669', 'CH_673', 'GB_5019863', 'NZ_2335', 'JP_307', 'CH_373', 'GB_5026248', 'CH_1108', 'CH_536', 'CH_4', 'CDM_2110', 'CH_625', 'CH_412', 'CH_2115', 'GB_5020038', 'GB_5023348', 'GB_5027311', 'CH_411', 'CH_942', 'CH_667', 'GB_5017201', 'DE_5000738', 'CH_471', 'CH_126', 'GB_5017484', 'CH_122', 'GB_5000111', 'GB_5017094', 'NZ_1024', 'CH_64', 'GB_5018914', 'CH_540', 'CH_713', 'GB_5000507', 'GB_5019137', 'CH_670', 'AU_1055', 'CH_868', 'GB_5019814', 'CDM_2237', 'NZ_5380', 'NZ_4970', 'CDM_2027', 'RU_97', 'CH_530', 'CH_529', 'GB_5016742', 'CDM_2183', 'GB_5000316', 'CH_680', 'CH_404', 'CH_483', 'GB_5017436', 'GB_5020025', 'GB_5016807', 'GB_5016746', 'CDM_2130', 'CH_2075', 'JP_40', 'GB_5019458', 'CH_142', 'CH_453', 'CH_700', 'CH_788', 'CH_1094', 'JP_67', 'CDM_2136', 'GB_5017339', 'CDM_2132', 'GB_5024564', 'GB_5000977', 'CDM_2174', 'CH_114', 'NZ_5177', 'CH_549', 'CH_681', 'GB_5000521', 'GB_5000154', 'GB_5018992', 'GB_5019385', 'RU_53', 'CDM_2047', 'GB_5027205', 'CDM_2004', 'GB_5018038', 'CH_1039', 'CH_643', 'CDM_2131', 'CH_100', 'NZ_1150', 'AU_1439', 'CDM_2086', 'RU_38', 'GB_5019701', 'CDM_2229', 'CDM_2148', 'CH_1028', 'CH_52', 'CH_451', 'AU_1032', 'GB_5018082', 'JP_27', 'NZ_10151', 'CH_120', 'GB_5019459', 'NZ_1990', 'CDM_2134', 'CDM_2093', 'CH_784', 'GB_5000737', 'GB_5019038', 'AU_2231', 'CH_869', 'JP_11', 'CH_491', 'CH_499', 'JP_57', 'CH_2216', 'CH_587', 'CH_975', 'CH_534', 'AU_1012', 'CH_818', 'NZ_2804', 'GB_5019538', 'CDM_2200', 'CDM_2028', 'CH_973', 'CH_874', 'JP_66', 'CH_956', 'CH_634', 'CDM_2949', 'GB_5000115', 'CH_2244', 'CDM_2931', 'CH_507', 'JP_87', 'GB_5026290', nan, 'GB_5016958', 'CH_933', 'CH_1061', 'CDM_2168', 'CH_701', 'CH_903', 'CH_59', 'CH_1030', 'CH_2062', 'CH_146', 'GB_5019521', 'CH_492', 'CH_1073', 'CH_904', 'CH_410', 'AU_1036', 'GB_5016654', 'FR_5026300', 'GB_5018046', 'CH_495', 'CH_128', 'JP_29', 'CH_508', 'CH_565', 'CDM_2101', 'CDM_2118', 'RU_78', 'CH_489', 'RU_39', 'GB_5027635', 'CH_531', 'UA_1', 'CH_407', 'AU_1021', 'CH_98', 'CH_542', 'GB_5016774', 'JP_113', 'CDM_2014', 'CH_855', 'GB_5020003', 'CH_2074', 'RU_37', 'CDM_2056', 'CDM_2958', 'GB_5016741', 'AU_2649', 'GB_5017717', 'CDM_2615', 'CDM_2008', 'CH_2025', 'CH_449', 'GB_5017263', 'CH_2073', 'CH_626', 'GB_5019300', 'CDM_2108', 'CDM_2202', 'CDM_2044', 'IT_5026683', 'CH_494', 'CH_502', 'CH_860', 'CH_88', 'GB_5018855', 'CDM_2091', 'CDM_2037', 'CH_1098', 'CH_2171', 'CH_467', 'CDM_2163', 'CH_48', 'GB_5019308', 'CH_391', 'CDM_2011', 'GB_5018149', 'GB_5027461', 'NZ_2567', 'CDM_2104', 'JP_61', 'CDM_2029', 'GB_5000718', 'JP_143', 'CH_766', 'GB_5017751', 'NZ_1671', 'EU_2312', 'CH_786', 'GB_5016561', 'CDM_2098', 'GB_5020008', 'CDM_2063', 'NZ_1025', 'CH_1113', 'GB_5000145', 'CH_937', 'GB_5024760', 'CH_515', 'CDM_2064', 'GB_5019349', 'CH_50', 'AU_1024', 'GB_5017981', 'CH_405', 'CH_859', 'NZ_1033', 'CH_78', 'CH_694', 'CH_450', 'CDM_2162', 'CDM_2057', 'CH_2088', 'CH_982', 'GB_5000107', 'CDM_2087', 'CH_573', 'CH_141', 'JP_42', 'CDM_2048', 'NZ_1020', 'GB_5025960', 'GB_5016603', 'NZ_10149', 'CH_370', 'CDM_2023', 'RU_111', 'CH_1104', 'CH_582', 'CH_419', 'CH_770', 'CDM_2146', 'CH_415', 'CH_556', 'CH_2134', 'GB_5000142', 'JP_53', 'CH_513', 'GB_5023970', 'CH_107', 'GB_5017656', 'CH_576', 'CDM_2024', 'GB_5024063', 'AU_1321', 'GB_5019519', 'GB_5017352', 'CH_856', 'GB_5026179', 'CDM_2065', 'GB_5017608', 'RU_68', 'CH_2136', 'GB_5000421', 'CH_2277', 'CDM_2171', 'GB_5016929', 'CDM_2116', 'CH_1027', 'CH_813', 'CH_572', 'JP_118', 'CH_42', 'GB_5000132', 'GB_5026387', 'AU_2321', 'RU_105', 'RU_69', 'CH_1099', 'GB_5016691', 'CH_509', 'CH_1076', 'GB_5016651', 'CH_677', 'JP_41', 'RU_36', 'CH_58', 'CDM_2204', 'GB_5000488', 'CDM_2187', 'CH_493', 'NZ_1050', 'CH_562', 'CDM_2796', 'GB_5000381', 'CH_118', 'GB_5017788', 'CH_809', 'GB_5019065', 'JP_47', 'CH_728', 'RU_42', 'GB_5017428', 'CH_45', 'CDM_2032', 'CDM_2106', 'CH_514', 'CDM_2239', 'GB_5026241', 'CDM_2042', 'CDM_2149', 'RU_101', 'CH_462', 'CH_731', 'CH_490', 'GB_5016817', 'CH_488', 'JP_75', 'CH_140', 'JP_49', 'CH_617', 'CDM_2097', 'CH_44', 'RU_55', 'CH_1114', 'CH_702', 'CH_2300', 'CH_101', 'GB_5017924', 'CH_714', 'GB_5019419', 'CDM_2060', 'JP_68', 'CH_537', 'RU_41', 'RU_40', 'JP_37', 'GB_5018047', 'CH_614', 'CDM_2013', 'CH_1036', 'CDM_2207', 'GB_5000106', 'CDM_2556', 'CH_2229', 'GB_5018329', 'CDM_2182', 'JP_86', 'GB_5026700', 'CH_679', 'GB_5000621', 'CDM_2135', 'CH_853', 'JP_370', 'GB_5026723', 'GB_5024191', 'CDM_2140', 'CH_1106', 'CH_87', 'GB_5019264', 'CH_1037', 'CH_592', 'GB_5019536', 'CH_652', 'CH_129', 'CH_392', 'CH_416', 'GB_5017823', 'GB_5018903', 'GB_5018976', 'AU_1384', 'GB_5018268', 'GB_5001062', 'GB_5000091', 'JP_79', 'CDM_2085', 'CH_99', 'RU_48', 'CH_53', 'RU_33', 'CH_510', 'CH_692', 'CH_1062', 'CDM_2218', 'CH_546', 'CH_966', 'GB_5017280', 'CH_693', 'AU_1418', 'CH_414', 'AU_2848', 'CH_797', 'RU_61', 'JP_31', 'CDM_2092', 'GB_5018224', 'CH_2172', 'RU_90', 'CH_382', 'CH_848', 'GB_5001097', 'CDM_1000', 'CDM_2198', 'CDM_2035', 'CH_503', 'GB_5000135', 'CH_627', 'CH_381', 'NZ_1235', 'NZ_1065', 'RU_98', 'RU_118', 'CH_532', 'GB_5018949', 'GB_5000100', 'JP_18', 'GB_5017714', 'GB_5000715', 'CH_849', 'CDM_2077', 'JP_271', 'GB_5027786', 'RU_121', 'GB_5018995', 'GB_5001137', 'CH_959', 'CH_77', 'CDM_2007', 'CH_2213', 'RU_109', 'CDM_2052', 'GB_5021047', 'CH_538', 'GB_5019540', 'CH_972', 'JP_17', 'CH_996', 'NZ_10200', 'CH_2158', 'CH_623', 'NZ_1604', 'CH_152', 'CDM_2233', 'GB_5018492', 'CH_671', 'CH_447', 'RU_117', 'JP_203', 'CH_888', 'CH_560', 'CH_521', 'NZ_1194', 'CH_1060', 'CH_839', 'JP_48', 'CDM_2015', 'CDM_2099', 'CDM_2039', 'CDM_2139', 'CH_461', 'NZ_10039', 'RU_60', 'CH_861', 'RU_79', 'RU_115', 'GB_5018993', 'JP_77', 'GB_5034510', 'GB_5019388', 'CH_403', 'GB_5026283', 'CDM_2033', 'CDM_2427', 'CDM_2020', 'CH_581', 'CH_105', 'CDM_2231', 'CH_2078', 'CDM_2375', 'JP_471', 'CDM_2046', 'CH_838', 'CH_862', 'CH_2278', 'CH_2242', 'CH_497', 'CDM_2045', 'AU_1011', 'GB_5019280', 'GB_5016994', 'RU_89', 'CH_2', 'GB_5016510', 'CH_2196', 'CH_672', 'GB_5000102', 'CDM_2225', 'AU_2617', 'CH_500', 'CH_43', 'CDM_2115', 'CH_988', 'GB_5018846', 'GB_5019067', 'RU_102', 'GB_5024146', 'CH_1001', 'JP_30', 'GB_5019312', 'RU_107', 'CH_89', 'GB_5018242', 'GB_5019792', 'CH_130', 'GB_5018400', 'CH_153', 'GB_5019405', 'CH_771', 'GB_5019248', 'GB_5000240', 'CH_993', 'CH_196', 'GB_5001079', 'RU_47', 'CH_2208', 'CH_60', 'CDM_2051', 'CH_82', 'CH_653', 'CDM_2005', 'CH_544', 'GB_5000161', 'GB_5020032', 'CH_480', 'CH_134', 'CDM_2166', 'RU_66', 'CH_541', 'CH_139', 'CDM_2012', 'GB_5024038', 'CDM_2197', 'CH_2142', 'CH_2195', 'CH_632', 'CH_80', 'CH_772', 'CH_2203', 'JP_132', 'GB_5024112', 'AU_2813', 'RU_116', 'GB_5016740', 'CH_2182', 'CH_575', 'RU_120', 'JP_313', 'CH_81', 'CH_1047', 'CH_567', 'CH_649', 'JP_73', 'CH_644', 'CH_1090', 'RU_93', 'CH_629', 'CH_1096', 'GB_5016666', 'JP_437', 'AU_2155', 'CDM_2006', 'CDM_2084', 'NZ_4631', 'GB_5017590', 'CH_683', 'RU_50', 'GB_5000703', 'GB_5000503', 'CDM_2026', 'CH_524', 'CH_1053', 'JP_125', 'CH_501', 'CH_535', 'CH_1074', 'CH_138', 'CH_113', 'CH_477', 'GB_5026104', 'CH_51', 'CH_726', 'RU_52', 'GB_5023899', 'RU_108', 'GB_5017316', 'CH_1105', 'CDM_2199', 'NZ_1060', 'CH_948', 'CH_154', 'GB_5019361', 'RU_88', 'JP_34', 'CH_413', 'JP_100', 'NZ_1028', 'CH_485', 'CH_769', 'GB_5018884', 'RU_32', 'GB_5017511', 'JP_33', 'GB_5017046', 'GB_5019582', 'GB_5019784', 'GB_5017514', 'CH_637', 'CH_496', 'CH_150', 'CH_811', 'CH_131', 'GB_5018069', 'CH_133', 'GB_5018728', 'CH_117', 'GB_5018207', 'JP_36', 'CH_112', 'RU_46', 'RU_103', 'CH_512', 'CDM_2067', 'JP_198', 'CH_631', 'CH_569', 'JP_52', 'CH_897', 'RU_51', 'GB_5016457', 'CH_83', 'EU_5019151', 'GB_5016620', 'CH_830', 'GB_5019589', 'CH_705', 'GB_5018044', 'CDM_2865', 'CDM_2094', 'GB_5000457', 'GB_5017763', 'CH_615', 'CDM_2089', 'CH_487', 'CH_755', 'CH_505', 'CDM_2165', 'NZ_1744', 'RU_54', 'CH_74', 'CH_516', 'GB_5019930', 'CH_938', 'CH_1052', 'CH_798', 'CH_2283', 'CDM_2040', 'CDM_2409', 'GB_5017229', 'GB_5017196', 'GB_5027089', 'GB_5019816', 'CH_504', 'CH_71', 'CH_398', 'CH_476', 'CH_686', 'GB_5024052', 'CH_397', 'GB_5019250', 'CH_584', 'CH_1044', 'NZ_1149', 'AU_2916', 'JP_82', 'AU_1222', 'GB_5027266', 'CDM_2022', 'CH_282', 'CH_645', 'JP_58', 'CDM_2179', 'CDM_2784', 'CH_406', 'CH_47', 'CH_2246', 'GB_5026103', 'CH_580', 'GB_5000060', 'CDM_2109', 'CH_378'}

In [10]:
df_missing_accounts = df_parties[df_parties["account_id"].isin(missing_account_ids)]
#df_missing_accounts.info()

## Schemas

In [25]:
df_ = pd.read_csv(fn_eex, low_memory=False)
for col in df_.columns:
    print(f'"{col}": "{col}",')

"auction_name": "auction_name",
"auction_price_eur_per_tco2": "auction_price_eur_per_tco2",
"auction_volume_tco2": "auction_volume_tco2",
"average_bid_size": "average_bid_size",
"average_bids_per_bidder": "average_bids_per_bidder",
"average_volume_bid_per_bidder": "average_volume_bid_per_bidder",
"average_volume_won_per_bidder": "average_volume_won_per_bidder",
"contract": "contract",
"country": "country",
"cover_ratio": "cover_ratio",
"date": "date",
"maximum_bid_eur_per_tco2": "maximum_bid_eur_per_tco2",
"mean_price_eur_per_tco2": "mean_price_eur_per_tco2",
"median_price_eur_per_tco2": "median_price_eur_per_tco2",
"minimum_bid_eur_per_tco2": "minimum_bid_eur_per_tco2",
"number_of_bids_submitted": "number_of_bids_submitted",
"number_of_successful_bidders": "number_of_successful_bidders",
"number_of_successful_bids": "number_of_successful_bids",
"revenue_at_eur": "revenue_at_eur",
"revenue_be_eur": "revenue_be_eur",
"revenue_bg_eur": "revenue_bg_eur",
"revenue_cy_eur": "revenue_cy_eur",
"revenue_cz_eur": "revenue_cz_eur",
"revenue_de_eur": "revenue_de_eur",
"revenue_dk_eur": "revenue_dk_eur",
"revenue_ee_eur": "revenue_ee_eur",
"revenue_el_eur": "revenue_el_eur",
"revenue_es_eur": "revenue_es_eur",
"revenue_fi_eur": "revenue_fi_eur",
"revenue_fr_eur": "revenue_fr_eur",
"revenue_hr_eur": "revenue_hr_eur",
"revenue_hu_eur": "revenue_hu_eur",
"revenue_ie_eur": "revenue_ie_eur",
"revenue_innovation_fund_eur": "revenue_innovation_fund_eur",
"revenue_innovation_fund_rrf_eur": "revenue_innovation_fund_rrf_eur",
"revenue_is_eur": "revenue_is_eur",
"revenue_it_eur": "revenue_it_eur",
"revenue_li_eur": "revenue_li_eur",
"revenue_lt_eur": "revenue_lt_eur",
"revenue_lu_eur": "revenue_lu_eur",
"revenue_lv_eur": "revenue_lv_eur",
"revenue_modernisation_fund_eur": "revenue_modernisation_fund_eur",
"revenue_ms_rrf_eur": "revenue_ms_rrf_eur",
"revenue_mt_eur": "revenue_mt_eur",
"revenue_nl_eur": "revenue_nl_eur",
"revenue_no_eur": "revenue_no_eur",
"revenue_pl_eur": "revenue_pl_eur",
"revenue_pt_eur": "revenue_pt_eur",
"revenue_ro_eur": "revenue_ro_eur",
"revenue_se_eur": "revenue_se_eur",
"revenue_si_eur": "revenue_si_eur",
"revenue_sk_eur": "revenue_sk_eur",
"revenue_social_climate_fund_eur": "revenue_social_climate_fund_eur",
"standard_deviation_bid_volume_per_bidder": "standard_deviation_bid_volume_per_bidder",
"standard_deviation_volume_won_per_bidder": "standard_deviation_volume_won_per_bidder",
"status": "status",
"time": "time",
"total_amount_of_bids": "total_amount_of_bids",
"total_number_of_bidders": "total_number_of_bidders",
"total_revenue_eur": "total_revenue_eur",
"datetime": "datetime",
"created_at": "created_at",

In [28]:
column_mapping = {
    "auction_name": "auction_name",
"auction_price_eur_per_tco2": "auction_price_eur_per_tco2",
"auction_volume_tco2": "auction_volume_tco2",
"average_bid_size": "average_bid_size",
"average_bids_per_bidder": "average_bids_per_bidder",
"average_volume_bid_per_bidder": "average_volume_bid_per_bidder",
"average_volume_won_per_bidder": "average_volume_won_per_bidder",
"contract": "contract",
"country": "country",
"cover_ratio": "cover_ratio",
"date": "date",
"maximum_bid_eur_per_tco2": "maximum_bid_eur_per_tco2",
"mean_price_eur_per_tco2": "mean_price_eur_per_tco2",
"median_price_eur_per_tco2": "median_price_eur_per_tco2",
"minimum_bid_eur_per_tco2": "minimum_bid_eur_per_tco2",
"number_of_bids_submitted": "number_of_bids_submitted",
"number_of_successful_bidders": "number_of_successful_bidders",
"number_of_successful_bids": "number_of_successful_bids",
"revenue_at_eur": "revenue_at_eur",
"revenue_be_eur": "revenue_be_eur",
"revenue_bg_eur": "revenue_bg_eur",
"revenue_cy_eur": "revenue_cy_eur",
"revenue_cz_eur": "revenue_cz_eur",
"revenue_de_eur": "revenue_de_eur",
"revenue_dk_eur": "revenue_dk_eur",
"revenue_ee_eur": "revenue_ee_eur",
"revenue_el_eur": "revenue_el_eur",
"revenue_es_eur": "revenue_es_eur",
"revenue_fi_eur": "revenue_fi_eur",
"revenue_fr_eur": "revenue_fr_eur",
"revenue_hr_eur": "revenue_hr_eur",
"revenue_hu_eur": "revenue_hu_eur",
"revenue_ie_eur": "revenue_ie_eur",
"revenue_innovation_fund_eur": "revenue_innovation_fund_eur",
"revenue_innovation_fund_rrf_eur": "revenue_innovation_fund_rrf_eur",
"revenue_is_eur": "revenue_is_eur",
"revenue_it_eur": "revenue_it_eur",
"revenue_li_eur": "revenue_li_eur",
"revenue_lt_eur": "revenue_lt_eur",
"revenue_lu_eur": "revenue_lu_eur",
"revenue_lv_eur": "revenue_lv_eur",
"revenue_modernisation_fund_eur": "revenue_modernisation_fund_eur",
"revenue_ms_rrf_eur": "revenue_ms_rrf_eur",
"revenue_mt_eur": "revenue_mt_eur",
"revenue_nl_eur": "revenue_nl_eur",
"revenue_no_eur": "revenue_no_eur",
"revenue_pl_eur": "revenue_pl_eur",
"revenue_pt_eur": "revenue_pt_eur",
"revenue_ro_eur": "revenue_ro_eur",
"revenue_se_eur": "revenue_se_eur",
"revenue_si_eur": "revenue_si_eur",
"revenue_sk_eur": "revenue_sk_eur",
"revenue_social_climate_fund_eur": "revenue_social_climate_fund_eur",
"standard_deviation_bid_volume_per_bidder": "standard_deviation_bid_volume_per_bidder",
"standard_deviation_volume_won_per_bidder": "standard_deviation_volume_won_per_bidder",
"status": "status",
"time": "time",
"total_amount_of_bids": "total_amount_of_bids",
"total_number_of_bidders": "total_number_of_bidders",
"total_revenue_eur": "total_revenue_eur",
"datetime": "datetime",
"created_at": "created_at",
}

df = (
    df_
    .assign(
        date = lambda x: pd.to_datetime(x["date"], utc=True),
        created_at = lambda x: pd.to_datetime(x["created_at"], utc=True),
        datetime = lambda x: pd.to_datetime(x["datetime"], utc=True),
    )
    .rename(columns=column_mapping)
)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 62 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   auction_name                              57 non-null     str
 1   auction_price_eur_per_tco2                57 non-null     float64
 2   auction_volume_tco2                       57 non-null     int64
 3   average_bid_size                          57 non-null     float64
 4   average_bids_per_bidder                   57 non-null     float64
 5   average_volume_bid_per_bidder             57 non-null     float64
 6   average_volume_won_per_bidder             57 non-null     float64
 7   contract                                  57 non-null     str
 8   country                                   57 non-null     str
 9   cover_ratio                               57 non-null     float64
 10  date                                      57 non-null     datetime64[us, UTC]
 11  maximum_bid_eur_per_tco2                  57 non-null     float64
 12  mean_price_eur_per_tco2                   57 non-null     float64
 13  median_price_eur_per_tco2                 57 non-null     float64
 14  minimum_bid_eur_per_tco2                  57 non-null     float64
 15  number_of_bids_submitted                  57 non-null     int64
 16  number_of_successful_bidders              57 non-null     int64
 17  number_of_successful_bids                 57 non-null     int64
 18  revenue_at_eur                            38 non-null     float64
 19  revenue_be_eur                            38 non-null     float64
 20  revenue_bg_eur                            38 non-null     float64
 21  revenue_cy_eur                            38 non-null     float64
 22  revenue_cz_eur                            38 non-null     float64
 23  revenue_de_eur                            12 non-null     float64
 24  revenue_dk_eur                            38 non-null     float64
 25  revenue_ee_eur                            38 non-null     float64
 26  revenue_el_eur                            38 non-null     float64
 27  revenue_es_eur                            38 non-null     float64
 28  revenue_fi_eur                            38 non-null     float64
 29  revenue_fr_eur                            38 non-null     float64
 30  revenue_hr_eur                            38 non-null     float64
 31  revenue_hu_eur                            38 non-null     float64
 32  revenue_ie_eur                            38 non-null     float64
 33  revenue_innovation_fund_eur               38 non-null     float64
 34  revenue_innovation_fund_rrf_eur           38 non-null     float64
 35  revenue_is_eur                            38 non-null     float64
 36  revenue_it_eur                            38 non-null     float64
 37  revenue_li_eur                            38 non-null     float64
 38  revenue_lt_eur                            38 non-null     float64
 39  revenue_lu_eur                            38 non-null     float64
 40  revenue_lv_eur                            38 non-null     float64
 41  revenue_modernisation_fund_eur            38 non-null     float64
 42  revenue_ms_rrf_eur                        38 non-null     float64
 43  revenue_mt_eur                            38 non-null     float64
 44  revenue_nl_eur                            38 non-null     float64
 45  revenue_no_eur                            38 non-null     float64
 46  revenue_pl_eur                            7 non-null      float64
 47  revenue_pt_eur                            38 non-null     float64
 48  revenue_ro_eur                            38 non-null     float64
 49  revenue_se_eur                            38 non-null     float64
 50  revenue_si_eur                            38 non-null     float64
 51  revenue_sk_eur                            38 non-null     float64
 52  revenue_social_climate_fund_eur           38 non-null     float64
 53  standard_deviation_bid_volume_per_bidder  57 non-null     float64
 54  standard_deviation_volume_won_per_bidder  57 non-null     float64
 55  status                                    57 non-null     str
 56  time                                      57 non-null     str
 57  total_amount_of_bids                      57 non-null     int64
 58  total_number_of_bidders                   57 non-null     int64
 59  total_revenue_eur                         57 non-null     float64
 60  datetime                                  57 non-null     datetime64[us, UTC]
 61  created_at                                57 non-null     datetime64[us, UTC]
dtypes: datetime64[us, UTC](3), float64(48), int64(6), str(5)
memory usage: 31.2 KB

In [23]:
df[df["installation_id"].duplicated(keep=False)]

      installation_id  nace_2015  nace_2020
1862          DE_1486      35.11      35.11
1863          DE_1486      35.11      35.11
3528            DE_74      23.51      23.51
3529            DE_74      23.51      23.51
3540            DE_75      23.51      23.51
3541            DE_75      23.51      23.51
3823            DK_11      35.30      35.30
3824            DK_11      35.30      35.30
3835            DK_12      35.30      35.30
3836            DK_12      35.30      35.30
9547             HU_3      35.11      35.11
9548             HU_3      35.11      35.11
13850           RO_88      35.11      35.11
13851           RO_88      35.11      35.11
15037           SK_57      23.51      23.51
15038           SK_57      23.51      23.51