In [1]:
import pandas as pd

from eutl_scraper.extract import extract_projects_from_transactions

In [2]:
df = pd.read_csv("data/normalized/eutl_transactions.csv")

C:\Users\abrel\AppData\Local\Temp\ipykernel_13592\3091830925.py:1: DtypeWarning: Columns (20,22,23,24,25,26,27,28,29,47,49,50,51,52,53,54,55,56,60,62,65,71,73) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/normalized/eutl_transactions.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2142475 entries, 0 to 2142474
Data columns (total 74 columns):
 #   Column                                                   Dtype
---  ------                                                   -----
 0   transaction_id                                           object
 1   transaction_type                                         object
 2   transaction_date                                         object
 3   transaction_status                                       object
 4   transferring_registry_name                               object
 5   transferring_account_type1                               float64
 6   transferring_account_type2                               object
 7   transferring_account_type3                               object
 8   transferring_account_open_dt                             object
 9   transferring_account_end_of_validity                     object
 10  transferring_account_name                                object
 11  transferring_account_identifier                          float64
 12  transferring_account_holder                              object
 13  transferring_account_holder_address1                     object
 14  transferring_account_holder_address2                     object
 15  transferring_account_holder_city                         object
 16  transferring_account_holder_postal_code                  object
 17  transferring_account_holder_country_code                 object
 18  transferring_account_holder_company_registration_number  object
 19  transferring_account_holder_lei                          object
 20  transferring_installation_name                           object
 21  transferring_installation_installation_identifier        float64
 22  transferring_installation_permit_identifier              object
 23  transferring_installation_parent_company                 object
 24  transferring_installation_subsidiary_company             object
 25  transferring_installation_eper_identification            object
 26  transferring_installation_city                           object
 27  transferring_installation_postal_code                    object
 28  transferring_installation_address1                       object
 29  transferring_installation_address2                       object
 30  transferring_installation_main_activity                  object
 31  acquiring_registry_name                                  object
 32  acquiring_account_type1                                  int64
 33  acquiring_account_type2                                  object
 34  acquiring_account_type3                                  object
 35  acquiring_account_open_dt                                object
 36  acquiring_account_end_of_validity                        object
 37  acquiring_account_name                                   object
 38  acquiring_account_identifier                             int64
 39  acquiring_account_holder                                 object
 40  acquiring_account_holder_address1                        object
 41  acquiring_account_holder_address2                        object
 42  acquiring_account_holder_city                            object
 43  acquiring_account_holder_postal_code                     object
 44  acquiring_account_holder_country_code                    object
 45  acquiring_account_holder_company_registration_number     object
 46  acquiring_account_holder_lei                             object
 47  acquiring_installation_name                              object
 48  acquiring_installation_installation_identifier           float64
 49  acquiring_installation_permit_identifier                 object
 50  acquiring_installation_parent_company                    object
 51  acquiring_installation_subsidiary_company                object
 52  acquiring_installation_eper_identification               object
 53  acquiring_installation_city                              object
 54  acquiring_installation_postal_code                       object
 55  acquiring_installation_address1                          object
 56  acquiring_installation_address2                          object
 57  acquiring_installation_main_activity                     object
 58  originating_registry_id                                  object
 59  unit_type_description                                    object
 60  supp_unit_type_description                               object
 61  original_period_code                                     int64
 62  lulucf_code_description                                  object
 63  project_identifier                                       float64
 64  track                                                    float64
 65  expiry_date                                              object
 66  amount                                                   int64
 67  acquiring_registry_id                                    object
 68  transferring_registry_id                                 object
 69  ets_id                                                   object
 70  acquiring_account_id                                     object
 71  acquiring_installation_id                                object
 72  transferring_account_id                                  object
 73  transferring_installation_id                             object
dtypes: float64(6), int64(4), object(64)
memory usage: 1.2+ GB

In [4]:
df_projects = extract_projects_from_transactions(df)
df_projects.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3551 entries, 0 to 2141086
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   originating_registry_id  3551 non-null   object
 1   amount                   3551 non-null   int64
 2   project_identifier       3551 non-null   float64
 3   lulucf_code_description  26 non-null     object
 4   track                    531 non-null    float64
 5   expiry_date              24 non-null     datetime64[ns]
 6   project_type             3550 non-null   object
 7   project_id               3551 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 249.7+ KB

In [6]:
df_accounts[df_accounts["registry_id"].isna()]

Empty DataFrame
Columns: [account_id, installation_id, registry_id, registry_name, account_type1, account_type2, account_type3, account_open_dt, account_end_of_validity, account_name, account_identifier, account_holder, account_holder_address1, account_holder_address2, account_holder_city, account_holder_postal_code, account_holder_country_code, account_holder_company_registration_number, account_holder_lei, installation_name, installation_installation_identifier, installation_permit_identifier, installation_parent_company, installation_subsidiary_company, installation_eper_identification, installation_city, installation_postal_code, installation_address1, installation_address2, installation_main_activity]
Index: []

[0 rows x 30 columns]

In [8]:
df.snapshot_date.min()

AttributeError: 'DataFrame' object has no attribute 'snapshot_date'

In [7]:
transaction_columns = [
    "transaction_id",
    "transaction_type",
    "transaction_date",
    # "transaction_status",  # drop status as we anyways only observe 'completed'
    "ets_id",
    "originating_registry",
    "acquiring_registry_id",
    "acquiring_account_id",
    "acquiring_installation_id",
    "transferring_registry_id",
    "transferring_account_id",
    "transferring_installation_id",
    "unit_type_description",
    "supp_unit_type_description",
    "amount",
]
df_trans = df[transaction_columns].copy()

KeyError: "['originating_registry'] not in index"

In [ ]:
df_trans["unit_type"] = list(
    zip(df_trans.unit_type_description, df_trans.supp_unit_type_description)
)
df_trans.unit_type.unique()

array([('ERU - Emission Reduction Unit', 'No supplementary unit type'),
       ('ERU - Converted from an RMU', 'No supplementary unit type'),
       ('CER - Certified Emission Reduction Unit converted from an AAU', 'No supplementary unit type'),
       ('RMU - Removal Unit', 'No supplementary unit type'),
       ('AAU - Assigned Amount Unit', 'No supplementary unit type'),
       ('Non-Kyoto Unit', 'EU Aviation Allowances (EUAA)'),
       ('AAU - Assigned Amount Unit', 'Allowance issued for the 2008-2012 period and subsequent 5-year periods and is converted from an AAU'),
       ('Non-Kyoto Unit', 'Swiss Aviation Allowances (CHUA)'),
       ('Non-Kyoto Unit', 'Allowance issued for the 2008 to 2012 and subsequent five-year periods by a Member State that does not have AAUs'),
       ('ERU - Emission Reduction Unit', nan),
       ('tCER - Temporary CER', nan),
       ('Non-Kyoto Unit', 'EU General Allowances (EUA)'),
       ('ERU - Converted from an RMU', nan),
       ('CER - Certified Emission Reduction Unit converted from an AAU', nan),
       ('RMU - Removal Unit', nan), ('AAU - Assigned Amount Unit', nan),
       ('Non-Kyoto Unit', 'Allowance issued for the 2005-2007 period and not converted from an AAU or other Kyoto unit'),
       ('Non-Kyoto Unit', 'Swiss General Allowances (CHU)'),
       ('tCER - Temporary CER', 'No supplementary unit type')],
      dtype=object)

In [ ]:
df_trans.tail()

,transaction_id,transaction_type,transaction_date,ets_id,originating_registry,acquiring_registry_id,acquiring_account_id,acquiring_installation_id,transferring_registry_id,transferring_account_id,transferring_installation_id,unit_type_description,supp_unit_type_description,amount
2142470,EU542433,10-2,2020-01-09 18:14:20,euets,EU,EU,EU_5016380,NaN,ES,ES_5008918,ES_160,Non-Kyoto Unit,EU General Allowances (EUA),879
2142471,FR93298,10-0,2009-05-07 17:26:34,euets,PT,NaN,NaN,NaN,NaN,NaN,NaN,AAU - Assigned Amount Unit,Allowance issued for the 2008-2012 period and ...,2444
2142472,FR10339,10-0,2006-06-01 16:34:39,euets,HU,NaN,NaN,NaN,NaN,NaN,NaN,Non-Kyoto Unit,Allowance issued for the 2005-2007 period and ...,1130
2142473,EU403486,10-2,2017-04-27 13:28:12,euets,EU,EU,EU_5016380,NaN,RO,RO_5010063,RO_110,Non-Kyoto Unit,EU General Allowances (EUA),60109
2142474,EU528943,10-0,2019-08-23 13:43:04,euets,EU,HU,HU_5011776,HU_146,NL,NL_5017659,NaN,Non-Kyoto Unit,EU General Allowances (EUA),1602